### ISSUE TITLE
Update API `park_events/stats` zo dat die > 30 dagen parkeerduur teruggeeft

### ISSUE THREAD

**Issue by bartwr** [Stichting-CROW/dashboarddeelmobiliteit-api#6]
Recent hebben we een filter op [> 30 dagen parkeerduur](https://github.com/Stichting-CROW/dashboarddeelmobiliteit-app/issues/178) toegevoegd aan de UI.

Er moet ook een API end point aangepast worden om dit goed te laten werken.

- Als de app
- Wil ik de `/park_events/stats` van > 30 dagen terugkrijgen via de API
- Zodat ik die kan tonen in de meta stats infobox

Voorbeeld API call:
https://api.dashboarddeelmobiliteit.nl/dashboard-api/v2/park_events/stats?x=1&zone_ids=34217&timestamp=2023-12-11T19:45:37Z

Voorbeeld API response:
![Image](https://github.com/Stichting-CROW/dashboarddeelmobiliteit-api/assets/899234/b40e77ea-66af-4807-96f2-2c6ce25837cd)

In plaats van 4 waardes onder `stats` moeten er 5 waardes terugkomen.

**Comment by sven4all** [comment]
Aangepast
